### ISSUE TITLE
Generated project has Windows new line characters

### ISSUE THREAD

**Issue by eddiezane** [sahat/megaboilerplate#79] opened 2016-06-08 14:56 UTC
![screen shot 2016-06-08 at 10 55 56 am](https://cloud.githubusercontent.com/assets/959573/15898802/9bfefd0e-2d67-11e6-8596-0f8f9381fab4.png)

**Comment by eddiezane** [comment] 2016-06-08 14:59
Actually it appears to just be `server.js`

**Comment by sahat** [comment] 2016-06-08 15:06
Hey @eddiezane, what's the easiest way to convert those to LF? I am currently on a Mac and `server.js` seems to be properly set to UNIX LF line separator.

**Comment by eddiezane** [comment] 2016-06-08 15:16
On a Mac as well.

Just reproduced with a fresh download.

Selection:

* Node.js
* Express
* Handlebars
* None
* PostCSS
* React
* Webpack
* Mocha
* PostgreSQL
* Email
* None

[dos2unix](http://linuxcommand.org/man_pages/dos2unix1.html) should be able to convert.

Awesome work on this btw!

**Comment by sahat** [comment] 2016-06-08 15:52
Thanks @eddiezane.

Looks good here after running dos2unix command: `find ./ -type f -exec dos2unix {} \;`.

Could it be because website is hosted in the Windows environment (Azure) files are generated with CRLF? Doesn't happen when I am generating files locally, but can reproduce on http://megaboilerplate.com.

**Comment by sahat** [comment] 2016-06-08 15:54
If this is not urgent, I was planning to migrate Mega Boilerplate to Heroku in the next few days. That should fix the CRLF issue.

**Comment by sahat** [comment] 2016-06-15 20:36
Should be fixed now that Mega Boilerplate is hosted on Heroku.

**Closed by sahat** 2016-06-15 20:36 UTC
